version: '3'

services:
  db:
      image: postgres
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres1234
        - POSTGRES_DB=claim
      ports:
      - "5436:5432"
  #redis:
  #  image: redis
  #  restart: always
  #  ports:
  #    - '6371:6379'
   
volumes:
      postgres_data: 
