services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=claim
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - '6379:6379'

  payment:
    build: .
    tty: true 
    command: python subscriber.py
    depends_on:
      - redis

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - db:postgres
    environment:
      - PGWEB_DATABASE_URL=postgresql://postgres:postgres1234@db:5432/claim?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data:
